export const gamesList = [
  { title: 'Endless Runner', file: 'endlessRunner.js' },
  { title: 'Subway Escape', file: 'subwayEscape.js' },
  { title: 'Flappy Space', file: 'flappySpace.js' },
  { title: 'Stack Game', file: 'stackGame.js' },
  { title: 'Sky Jump', file: 'skyJump.js' },
  { title: 'Racing Game', file: 'racingGame.js' },
  { title: 'Snake Evolution', file: 'snakeEvolution.js' },
  { title: 'Brick Breaker', file: 'brickBreaker.js' },
  { title: 'Space Shooter', file: 'spaceShooter.js' },
  { title: 'Memory Game', file: 'memoryGame.js' },
  { title: 'Tic Tac Toe AI', file: 'ticTacToeAI.js' },
  { title: 'Puzzle Block', file: 'puzzleBlock.js' },
  { title: 'Tower Defense', file: 'towerDefense.js' },
  { title: 'Fruit Slice', file: 'fruitSlice.js' },
  { title: 'Car Dodge', file: 'carDodge.js' },
  { title: '2048', file: 'game2048.js' },
  { title: 'Color Match', file: 'colorMatch.js' },
  { title: 'Whack-A-Mole', file: 'whackAMole.js' },
  { title: 'Ball Bounce', file: 'ballBounce.js' },
  { title: 'Tap Dash', file: 'tapDash.js' },
  { title: 'Multiplayer Arena', file: 'multiplayerArena.js' },
];
